### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by ronnievisser** [UpCloudLtd/upcloud-php-api#1]
Hi,

I want to use this package to build automation. however I'm unable to install this package.

1. I believe the name in composer.json file is incorrect
2. The package does not exists on packagist

I think you move it stable once above has been arranged.

Hope you guys can fix this soon.

Thanks

**Comment by iler** [comment]
Hi!

Thanks for reporting this issue in. We will have a look at this and update here when we know more about it. We will try to fit it as soon as possible!

**Comment by ronnievisser** [comment]
Great!

to give you more info: this error displays even when setting the minimum-stability to dev

Could not find a matching version of package upcloudltd/upcloud-php-api. Check the package spelling, your version constraint and that  
   the package is available in a stability which matches your minimum-stability (dev).

**Comment by mlackman** [comment]
Hello,
I made a fork from the upcloud-php-api, where I try to fix the issue. @ronnievisser would you be so kind and try it out. Note that the README instructions has been updated and the original instructions are not valid. The fork can be found from https://github.com/mlackman/upcloud-php-api. 
I changed the package name to upcloudltd/upcloud-php-api and changed the example snippet of getting the account information.

**Comment by ronnievisser** [comment]
Hi,

Here is what I believe should be done. becuase this is not working. first of all If you release a package in dev stability nobody will install it becuase nobody wants there production app to use dev as a minimum stability.

1. you must make sure that the package exists on https://packagist.org. otherwise composer will not recognize it.

2. the following part is not needed and can be removed from the readme since the repository is public accessable.
````json"repositories": 
[
    {
      "type": "git",
      "url": "https://github.com/mlackman/upcloud-php-api.git"
    }
  ],"
````
3. remove the dev dependency

**Comment by ronnievisser** [comment]
Do you have any ETA when this will be fixed?

**Comment by iler** [comment]
@ronnievisser we are fixing this at the moment and are hoping to get it fixed during this week. We identified also some other problems for example with test coverage that we are also fixing. Sorry for the wait but we are doing our best to get this fixed as soon as possible.

**Comment by ronnievisser** [comment]
any news when I can work with it?

**Comment by mlackman** [comment]
I made a packagist packege, https://packagist.org/packages/upcloudltd/upcloud-php-api
If this is all that is needed, I can close this issue

**Comment by ronnievisser** [comment]
thank you! I managed to install v1.0.0
