### ISSUE TITLE
Documentation needs update

### ISSUE THREAD

**Issue by ronnievisser** [UpCloudLtd/upcloud-php-api#10]
Hi,

It seemd that the documentation not referencing the correct namespaces. 

In the documentation you reference ServerApi from
```php
Upcloud\ApiClient\Api\ServerApi
```

but it must be
```php
Upcloud\ApiClient\Upcloud\ServerApi
```

**Comment by ronnievisser** [comment]
also Guzzle path is incorrect.

**Comment by iler** [comment]
@ronnievisser thanks for noticing these. If you could make a PR to fix these it would be highly appreciated!

**Comment by ronnievisser** [comment]
Sorry but I don't have time for that!

another issue. regarding the xamples you only nee to pass in a Guzzle client but the config is also required otherwise it will not be able to connect to your backend.

**Comment by iler** [comment]
@ronnievisser no problem!

Regarding this issue just making sure that I have correctly understood to which documentation you are referring to. I assume it's this and all the equivalents https://github.com/UpCloudLtd/upcloud-php-api/blob/master/docs/Api/ServerApi.md#example?

**Comment by ronnievisser** [comment]
I believe it’s related to all of them!

**Comment by iler** [comment]
@ronnievisser Sorry for the delay here but we have finally fixed the docs. If you still see something odd please ping here. If not we can close this issue.
