### ISSUE TITLE
Zone API returning empty 'name' column while 'id' is expected

### ISSUE THREAD

**Issue by Cannonb4ll** [UpCloudLtd/upcloud-php-api#14]
I am using this package for reference.

Currently trying to get the Zones through this package, which works but I am not getting the 'id' column, I am getting an empty/null 'name' column. (See image below)

Your documentation @ https://www.upcloud.com/api/5-zones/#zones states that it should return an ID and description.

What is going wrong?

![Image](http://screenshot.dennissmink.nl/0e14a72f6779/Image%202018-10-13%20at%209.13.54%20AM.png)

**Comment by Cannonb4ll** [comment]
My code:

```
        $upCloud = new \Upcloud\ApiClient\Upcloud\ZoneApi();
        $config = $upCloud->getConfig();
        $config->setUsername('***');
        $config->setPassword('***');

        dd($upCloud->listZones());
```

**Comment by Cannonb4ll** [comment]
For now hardcoded in our console command job, but really want to make this dynamic through api:

```php
        $plans = [
            [
                'name' => 'Frankfurt #1',
                'id' => 'de-fra1'
            ],
            [
                'name' => 'Helsinki #1',
                'id' => 'fi-hel1'
            ],
            [
                'name' => 'Amsterdam #1',
                'id' => 'nl-ams1'
            ],
            [
                'name' => 'Singapore #1',
                'id' => 'sg-sin1'
            ],
            [
                'name' => 'London #1',
                'id' => 'uk-lon1'
            ],
            [
                'name' => 'Chicago #1',
                'id' => 'us-chi1'
            ],
        ];
```

**Comment by Darep** [comment]
Oh, sorry about that! Glad that you found a workaround 👍 Yeah the "name" field should be "id" in the result, seems like it was mis-named in the Zone model. We'll have a look at that!

**Comment by Darep** [comment]
PR at https://github.com/UpCloudLtd/upcloud-php-api/pull/15
