### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Upcloud\ApiClient\Api\StorageApi'

### ISSUE THREAD

**Issue by vicky1hr** [UpCloudLtd/upcloud-php-api#16]
When i am going to get the templates using this API. I am getting the below error. Please help me to out from this error.

**PHP Fatal error:  Uncaught Error: Class 'Upcloud\ApiClient\Api\StorageApi' not found in dashboard/UpCloud/upcloud-php-api-master/UpCloud.php:65
Stack trace:
#0 dashboard/UpCloud/upcloud-php-api-master/UpCloud.php(27): UpCloudAPI->ListStorage()
#1 {main}
  thrown in dashboard/UpCloud/upcloud-php-api-master/UpCloud.php on line 65**

**Comment by mlackman** [comment]
Hi, could you try following code: 
```
<?php
require_once(__DIR__ . '/vendor/autoload.php');

$api_instance = new Upcloud\ApiClient\Upcloud\AccountApi();
$config = $api_instance->getConfig();
$config->setUsername('username');
$config->setPassword('password');

$storage = new Upcloud\ApiClient\Upcloud\StorageApi();
echo $storage->listStorages();

?>
```
There seem to be some misinformation in our documentation. We will fix the documentation, sorry for your trouble.

**Comment by vicky1hr** [comment]
Yes I used this code after that it was working fine.

And I need one more help from you.

How to pass ssh_keys in server creation php API .

Please help me regarding this...

**Comment by mlackman** [comment]
I'm afraid that adding ssh keys is not currently possible with the api

**Comment by vicky1hr** [comment]
Thank you for the response.

Is there any other way to do it using PHP.

**Comment by mlackman** [comment]
By using some PHP REST client, you can use our public REST api. Documentation can be found from https://developers.upcloud.com 

And for creating the server: https://developers.upcloud.com/8-servers/#create-server. The ssh key is given in login_user object.

**Comment by vicky1hr** [comment]
How to pass Authorization in this REST API using php

Can I get the syntax to pass username and password.

I have tried with 
base64_encode(username:password);

But I got error unauthorization

**Comment by mlackman** [comment]
Authentication information can be found from: https://developers.upcloud.com/2-architecture/ 
It is HTTP Basic access authentication, instruction for constructing authorization header can be found from  https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization

I think it would be easier to use like http://phphttpclient.com/ rest client. It has method for setting basic auth and sending json bodies etc.
