### ISSUE TITLE
Zone ID not available

### ISSUE THREAD

**Issue by rehmatworks** [UpCloudLtd/upcloud-php-api#17]
Zone ID not available when using `listZones()` method on `\Upcloud\ApiClient\Upcloud\ZoneApi`. Can anyone please confirm this issue? Here is what I get:

```php
Zone {#434 ▼
  #container: array:2 [▼
    "name" => null
    "description" => "Frankfurt #1"
  ]
}
```

Just description is available along with a null `name` key.

**Comment by rehmatworks** [comment]
Sorry, an older version was installed. Since I'm using this in Laravel, there is an issue installing the latest version in Laravel 5.8. There are a few dependency conflicts. Would you please be able to test and make it compatible with latest Laravel framework?

**Comment by Darep** [comment]
Did you get it working with Laravel? I'm not familiar with that framework so can't help much, though it might help someone else to know what happened if they run into same problem 😊
