### ISSUE TITLE
Get unique id of server after server creation

### ISSUE THREAD

**Issue by elindydotcom** [UpCloudLtd/upcloud-php-api#24]
When a server is created it returns what looks like a single server object.  But, using 
`$result->getUuid()`
results in an error - 'call to undefined method getUuid'.

getUuid is a getting defined in model/server.php

Any idea what I could be doing wrong?  I've taken the example from the home page of this project and just added the called to $result->getUuid() so not sure what I'm missing.

Thanks.

**Comment by elindydotcom** [comment]
Actually, it looks like if the createServer api returns a server response object and you need to use the getServer method first:

`$result->getServer()->getUuid()`

**Comment by ghost** [comment]
Glad you figured it out 🙂
