### ISSUE TITLE
How to send userid and ssh key to createServer

### ISSUE THREAD

**Issue by elindydotcom** [UpCloudLtd/upcloud-php-api#25]
The REST API seems to allow for it (https://developers.upcloud.com/1.3/8-servers/#create-server) but it 's not quite clear how to get it done in this PHP wrapper.

Thanks.

**Comment by elindydotcom** [comment]
This PR fixes this issue: https://github.com/UpCloudLtd/upcloud-php-api/pull/35

**Comment by Trdls** [comment]
As @cyruscollier replied to the PR

> Yes, v2 added user ssh key support, and #43 addressed the remaining lack of the delete storage flag. Closing this PR now.

So I will close this issue.
