### ISSUE TITLE
restartServer: New documentation example still returns authorization error.

### ISSUE THREAD

**Issue by elindydotcom** [UpCloudLtd/upcloud-php-api#32]
The documentation was updated after we reported issue #27.  However, running the updated example code still returns an authorization error.

**Comment by Trdls** [comment]
Hello. I tried this myself and everything worked perfectly. [Link to the docs I used](https://github.com/UpCloudLtd/upcloud-php-api/blob/master/docs/Api/ServerApi.md#restartServer)

```
require_once(__DIR__ . '/vendor/autoload.php');

// Configure HTTP basic authorization: baseAuth
Upcloud\ApiClient\Configuration::getDefaultConfiguration()->setUsername('YOUR_USERNAME');
Upcloud\ApiClient\Configuration::getDefaultConfiguration()->setPassword('YOUR_PASSWORD');

$api_instance = new Upcloud\ApiClient\Upcloud\ServerApi();
$server_id = "server_id_example"; // string | Id of server to restart
$restart_server = new \Upcloud\ApiClient\Model\RestartServer(); // \Upcloud\ApiClient\Model\RestartServer |

try {
    $result = $api_instance->restartServer($server_id, $restart_server);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling ServerApi->restartServer: ', $e->getMessage(), PHP_EOL;
}
```

Of course changing the user credentials to my own. And I used a sub account to be extra thorough. Could you share the code example you are using?

**Comment by elindydotcom** [comment]
Hi @PopoSensei - I reported this issue over a year ago. Since then there has been a major upgrade to the API.  So maybe that upgrade fixed this issue.  I have not tested this on the new major version.

Thanks.

**Comment by Trdls** [comment]
Yeah. Sorry that it has taken so long to respond. Hope it has been fixed in the major update. Feel free to open a new issue if it is still an issue. I'll close this for now.
