### ISSUE TITLE
listZones not returning zone tag

### ISSUE THREAD

**Issue by samituoh** [UpCloudLtd/upcloud-php-api#34]
When i call listZones it doesnt return zone tag eg. "fi-hel1" etc.

<img width="1328" alt="Screenshot 2020-03-10 12 02 31" src="https://user-images.githubusercontent.com/40687784/76301593-30811000-62c7-11ea-96bd-66f2002c0620.png">

**Comment by nbejansen** [comment]
Same issue here.

**Comment by Darep** [comment]
Hmm, strange. This was fixed in https://github.com/UpCloudLtd/upcloud-php-api/pull/15 and released as version 1.0.3. The "name" field in API was renamed to "id" some time ago.

**Comment by samituoh** [comment]
@Darep Yes. that id found from API but it wasnt on code.. i needed to make setter and getter for ID and after that it works.

**Comment by Darep** [comment]
Could you create a PR for your change?

**Comment by Trdls** [comment]
Fixed in #39
