### ISSUE TITLE
”virtio” is not a default value for ”nic_model” when creating a new upcloud server.

### ISSUE THREAD

**Issue by DmitryPotapenko7** [UpCloudLtd/upcloud-php-api#37]
The documentation said that ”virtio” is a default value for ”nic_model”
![image](https://user-images.githubusercontent.com/54019279/97693126-5c950f80-1aa9-11eb-803f-80d16bb4a536.png)
But this is not true. If we do not explicitly indicate the nic_model = 'virtio' via setNicModel setter in the code when creating a new upcloud server then the default value will be 'e1000'.
![image](https://user-images.githubusercontent.com/54019279/97693391-c6151e00-1aa9-11eb-9d8b-de23fabf85fa.png)
and this is a response from upcloud API
![image](https://user-images.githubusercontent.com/54019279/97693474-e349ec80-1aa9-11eb-88a7-bf7ab5a49dbc.png)
Thanks!

**Comment by Darep** [comment]
Good catch! Seems like there is an open PR which fixes this (among many other things which are getting modernized & up-to-date): https://github.com/UpCloudLtd/upcloud-php-api/pull/38

**Comment by Trdls** [comment]
This has been fixed in #39
